// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package css

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

const (
	GlassCard = "bg-gray-200 backdrop-blur-lg border border-gray-200 shadow-sm"
)

func AnimateBounce() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`animation:pinBounce 2.5s cubic-bezier(0.23, 1, 0.32, 1) infinite;`)
	templ_7745c5c3_CSSID := templ.CSSID(`AnimateBounce`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func AnimateLiveGlow() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`animation:liveGlow 2s ease-in-out infinite;`)
	templ_7745c5c3_CSSID := templ.CSSID(`AnimateLiveGlow`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func AnimateEtaPulse() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`animation:etaPulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;`)
	templ_7745c5c3_CSSID := templ.CSSID(`AnimateEtaPulse`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

var _ = templruntime.GeneratedTemplate
