// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/templui/templui/components/icon"
)

type stat struct {
	value string
	label string
	icon  templ.Component
}

var stats = []stat{
	{
		value: "340+",
		label: "Routes Covered",
		icon:  icon.Route(icon.Props{Class: "size-6 text-gray-950"}),
	},
	{
		value: "180K",
		label: "Daily Riders",
		icon:  icon.Users(icon.Props{Class: "size-6 text-gray-950"}),
	},
	{
		value: "98.4%",
		label: "System Uptime",
		icon:  icon.ShieldCheck(icon.Props{Class: "size-6 text-gray-950"}),
	},
	{
		value: "< 5ms",
		label: "Route Refresh",
		icon:  icon.Zap(icon.Props{Class: "size-6 text-gray-950"}),
	},
}

func Tracking() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"features\" class=\"py-28 px-6 relative overflow-hidden\"><div class=\"max-w-7xl mx-auto relative z-10\"><!-- Header --><div class=\"text-center mb-16 reveal\"><span class=\"inline-block text-blue-700 text-xs font-semibold tracking-[0.3em] uppercase bg-blue-50 px-4 py-1.5 rounded-full mb-4\">Real-Time Intelligence</span><h2 class=\"text-[clamp(2rem,5vw,3.5rem)] font-light text-foreground leading-tight\">Every route. Every bus.<br><span class=\"font-semibold italic\">Always live.</span></h2></div><!-- Stats row --><div class=\"grid grid-cols-2 md:grid-cols-4 gap-4 mb-16 reveal reveal-delay-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, s := range stats {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"bento-item rounded-3xl p-6 text-center\"><div class=\"size-10 bg-gray-50 rounded-2xl flex items-center justify-center mx-auto mb-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = s.icon.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><p class=\"text-2xl font-display font-semibold text-foreground\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(s.value)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/pages/landing/components/tracking.templ`, Line: 60, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p><p class=\"text-xs text-gray-500 mt-1 font-medium\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(s.label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/pages/landing/components/tracking.templ`, Line: 63, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div></section><script>\n        function scrollRevealInit() {\n            const reveals = document.querySelectorAll(\".reveal\")\n            // Start scoll-in-view observer\n            const observer = new IntersectionObserver((entries) => {\n                entries.forEach(entry => {\n                    // What to do when section is coming into view?\n                    if (entry.isIntersecting) {\n                        entry.target.classList.add('visible')\n                    }\n                })\n                // Trigger options :-\n                // - when 10% of the element is in view,\n                // - optional margin before triggering\n            }, { threshold: 1.0, rootMargin: '0px 0px -40px 0px' })\n\n            // Attach observer onto revealing section(s)\n            reveals.forEach(reveal => observer.observe(reveal))\n        }\n\n        document.addEventListener(\"DOMContentLoaded\", scrollRevealInit)\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
